files:
  - source: /custom_components/webuntis/translations/en.json
    translation: /custom_components/webuntis/translations/%two_letters_code%.json
    api_token: CROWDIN_PROJECT_ID
    project_id: CROWDIN_PERSONAL_TOKEN
