files:
  - source: /custom_components/webuntis/translations/en.json
    translation: /custom_components/webuntis/translations/%locale%.json
    languages_mapping:
      locale:
        de: de    
        nl: nl
