get_timetable:
  description: Get WebUntis timetable
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: webuntis
    start:
      required: true
      selector:
        date:
    end:
      required: true
      selector:
        date:
    apply_filter:
      required: true
      default: true
      selector:
        boolean:
    show_cancelled:
      required: true
      default: true
      selector:
        boolean:

count_lessons:
  description: Get WebUntis timetable
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: webuntis
    start:
      required: true
      selector:
        date:
    end:
      required: true
      selector:
        date:
    apply_filter:
      required: true
      default: true
      selector:
        boolean:
    count_cancelled:
      required: true
      default: false
      selector:
        boolean:
